### ISSUE TITLE
Don't support multi-client

### ISSUE THREAD

**Issue by keanuyaoo** [myDevicesIoT/cayennejs#2]
Don't support more then one client instance;
Error code at:  mqtt.js -53  :add the same route rule;

I temporary change the ':thingsId'  to the  real clientId ;

**Comment by asanchezdelc** [comment]
@keanuyaoo thanks for your suggestion. In our world `thingsId` its the `clientId`. It's not an error. However, we will work on supporting more than one client per instance.
