### ISSUE TITLE
404 mqtt.mydevices.com

### ISSUE THREAD

**Issue by bjoernbusch** [myDevicesIoT/cayennejs#6]
I was trying to get this sample to run, but I'm getting a 404 on mqtt.mydevices.com.

WebSocket connection to 'ws://mqtt.mydevices.com/' failed: Error during WebSocket handshake: Unexpected response code: 404

Any suggestions?

**Comment by asanchezdelc** [comment]
It’s an MQTT protocol not web socket. The README file contains example code on how to use this library.

**Comment by bjoernbusch** [comment]
I tried to integrate the sample code in an Angular app and this is the error that I get on the console. Has anybody tried this before?

**Comment by asanchezdelc** [comment]
Oh I see, yeah It won’t work with angular app or any front end framework. This is a backend library. For the time being you can do a MQTT to WS bridge.

**Comment by bjoernbusch** [comment]
ah ok, I wasn't aware of the difference between server and client side javascript code. I'll move everything to the server then.
