### ISSUE TITLE
unexpected token error while connecting LinkIt smart duo 7688  to Cayenne

### ISSUE THREAD

**Issue by BJSingh** [myDevicesIoT/cayennejs#7]
I am trying to connect LinkIt 7688 duo on Cayenne cloud using Nodejs library. Device installed with
npm  2.11.3 and node  0.12.7 versions.
I am getting following error shown in below screenshot
![screenshot1](https://user-images.githubusercontent.com/5358553/32718862-7c8440f6-c884-11e7-9079-25a0c4582ecf.PNG)

I have use demo code available on link-> https://github.com/myDevicesIoT/cayennejs

Same code was working on my windows 8.1 PC with npm 3.10.6 and node 6.9.1 version

**Comment by jburhenn** [comment]
It appears arrow functions are only supported in Node.js 4.0.0 and above. So you might try updating your Node.js version. Or if you need to use the old version you could try updating the example code to remove the arrow function. Here's a link that shows how the old syntax works: https://stackoverflow.com/questions/36843574/node-js-readline-unexpected-token. However, I'm not sure if the rest of the library will work well with the older version of Node.js so it's possible you may run into other errors.
